spryker-shop/b2b-demo-marketplace

- composer.json
- composer.lock
- integrator.lock
- src/Pyz/Yves/ProductSearchWidget/Theme/default/components/molecules/product-quick-add-form/product-quick-add-form.twig
- yarn.lock
Tickets:
- https://spryker.atlassian.net/browse/MP-5988
- https://spryker.atlassian.net/browse/MP-6732
- https://spryker.atlassian.net/browse/MP-6573
> FE bugs integration

- src/Pyz/Yves/ProductSearchWidget/Theme/default/views/product-quick-add/product-quick-add.twig
Ticket: https://spryker.atlassian.net/browse/MP-6835
Changes: fixed work of product search widget in cart and shopping list pages.
> MP-6835: added missing changes that prevented normal work of quick search widget

- composer.lock
Ticket: https://spryker.atlassian.net/browse/MP-6796
> MP-6796: integration of spryker/product-merchant-portal-gui update (fixes price editing in merchant portal)

- composer.lock
- src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
Ticket: https://spryker.atlassian.net/browse/MP-4088
Changelog:
* Update spryker/product-offer-storage package to the latest version
> MP-4088: integration of spryker/product-offer-storage update

- src/Pyz/Zed/Oms/OmsDependencyProvider.php
Ticket: https://spryker.atlassian.net/browse/MP-6788
> CC-17204 MP-6788 fixed calculation of product offer reservation

- .github/workflows/ci.yml
- deploy.ci.acceptance.mariadb.yml
- deploy.ci.acceptance.yml
https://spryker.atlassian.net/browse/CC-26176
> CC-26176: Add robot tests

- composer.json
- composer.lock
- config/Shared/config_default.php
- deploy.aop-b2b-testing.yml
- deploy.aop-demoshop-b2b.yml
- deploy.aws-env-template.yml
- deploy.ci.acceptance.mariadb.yml
- deploy.ci.acceptance.yml
- deploy.ci.api.mariadb.yml
- deploy.ci.api.yml
- deploy.ci.functional.mariadb.yml
- deploy.ci.functional.yml
- deploy.dev.yml
- deploy.spryker-mp-b2b.yml
- deploy.spryker-mpb2bs.yml
- deploy.yml
- Ticket: https://spryker.atlassian.net/browse/SUPESC-606
Reference all core PRs for auto-link back-references.
Core PRs
- https://github.com/spryker/spryker/pull/9959
> SUPESC-606 Fixed filtering by stores in Availability Notifications.

- config/Shared/config_default.php
- Ticket: https://spryker.atlassian.net/browse/CC-25997
> CC-25997 Lowered chunk size for search sync.

- composer.lock
- package-lock.json
- package.json
Ticket: https://spryker.atlassian.net/browse/SUPESC-660
Integration: https://spryker.atlassian.net/browse/CC-26545
> SUPESC-660 Updated `@spryker/oryx-for-zed` dependency version.

- src/Pyz/Yves/CartPage/Theme/default/components/molecules/cart-items-list/cart-items-list.twig
- src/Pyz/Yves/CartPage/Theme/default/components/molecules/cart-upselling/cart-upselling.twig
- src/Pyz/Yves/CartPage/Theme/default/components/molecules/product-cart-item/index.ts
- src/Pyz/Yves/CartPage/Theme/default/components/molecules/product-cart-item/product-cart-item.scss
- src/Pyz/Yves/CartPage/Theme/default/components/molecules/product-cart-item/product-cart-item.twig
- src/Pyz/Yves/CartPage/Theme/default/components/molecules/product-cart-items-list/product-cart-items-list.twig
- src/Pyz/Yves/CartPage/Theme/default/templates/page-layout-cart/page-layout-cart.twig
- src/Pyz/Yves/ProductReviewWidget/Theme/default/components/molecules/review-average-display/review-average-display.twig
- src/Pyz/Yves/ShopUi/Theme/default/components/molecules/product-card-item/product-card-item.twig
- Ticket: https://spryker.atlassian.net/browse/CC-26385
> CC-26385: Integrated ajax rendering of the cart page

- src/Pyz/Zed/EventDispatcher/EventDispatcherDependencyProvider.php
- Ticket: https://spryker.atlassian.net/browse/FRW-1209
> FRW-1209: Integrated redirect response whitelist

- data/import/common/common/product_alternative.csv
- Ticket: https://spryker.atlassian.net/browse/CC-16536
> CC-16536 Added alternative abstract products to the import file

- composer.lock
- data/import/common/common/glossary.csv
Core PR: https://github.com/spryker/spryker-shop/pull/2349
Ticket: https://spryker.atlassian.net/browse/CC-25966
> CC-25966 Added additional validation for company role form.

- composer.json
- composer.lock
- src/Pyz/Zed/CompanyUser/CompanyUserDependencyProvider.php
- Ticket: https://spryker.atlassian.net/browse/SUPESC-605
- Integration ticket: https://spryker.atlassian.net/browse/CC-27058
- Core PR: https://github.com/spryker/spryker/pull/10080
> SUPESC-605: Fix an exception on company user delete

- src/Pyz/Glue/EventDispatcher/EventDispatcherDependencyProvider.php
- src/Pyz/Glue/GlueBackendApiApplication/GlueBackendApiApplicationDependencyProvider.php
- Ticket: https://spryker.atlassian.net/browse/CC-28284
> CC-28284 Enabled runtime events for Backend API.

- composer.json
- composer.lock
- src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
- Ticket: https://spryker.atlassian.net/browse/CC-17164
- Core PR: https://github.com/spryker/spryker/pull/10154
> CC-17164 Fixed product offer availability when product offer is not assigned to a store.

- composer.json
- composer.lock
- src/Pyz/Client/ProductCategoryStorage/ProductCategoryStorageDependencyProvider.php
- Ticket: https://spryker.atlassian.net/browse/CC-26820
- Core PRs: 
- https://github.com/spryker/suite-nonsplit/pull/1846
- https://github.com/spryker/spryker/pull/7594
- https://github.com/spryker/spryker-shop/pull/791
> CC-26820 Fixed breadcrumbs for a product integration. 

- package-lock.json
Ticket: https://spryker.atlassian.net/browse/CC-29232
> CC-29232 Remove fs dependency

- .github/workflows/ci.yml
- composer.json
- composer.lock
Ticket: https://spryker.atlassian.net/browse/SDK-2812
> SDK-2812: Use evaluator version 0.1.0

- codeception.functional.yml
- tests/PyzTest/Zed/AppCatalogGui/Communication/Controller/AppCatalogGuiControllerCest.php
- tests/PyzTest/Zed/AppCatalogGui/_support/AppCatalogGuiCommunicationTester.php
- tests/PyzTest/Zed/AppCatalogGui/_support/PageObject/AppCatalogGuiApiLoginPage.php
- tests/PyzTest/Zed/AppCatalogGui/_support/PageObject/AppCatalogGuiIndexPage.php
- tests/PyzTest/Zed/AppCatalogGui/codeception.yml
- tests/PyzTest/Zed/MessageBroker/Business/SendMessageTest.php
- tests/PyzTest/Zed/MessageBroker/_support/MessageBrokerBusinessTester.php
- tests/PyzTest/Zed/MessageBroker/codeception.yml
- tests/PyzTest/Zed/OauthClient/Business/OAuthClientTest.php
- tests/PyzTest/Zed/OauthClient/_support/OauthClientBusinessTester.php
- tests/PyzTest/Zed/OauthClient/codeception.yml
- tsconfig.mp.json
- Ticket: https://spryker.atlassian.net/browse/APPS-7140
- Added tests for modules AppCatalogGui, MessageBroker and OauthClient, so new ACP ready functionality is covered by tests.
> APPS-7140: Message sending tests integration

- src/Pyz/Client/MultiCart/MultiCartConfig.php
- Ticket: https://spryker.atlassian.net/browse/CC-29660
> CC-29660 Fixed displaying approval statuses on shipping cart

- composer.json
- composer.lock
- Ticket: https://spryker.atlassian.net/browse/CC-27951
> CC-29908 Raised date time configurator version

- src/Pyz/Glue/GlueApplication/GlueApplicationConfig.php
- Ticket: https://spryker.atlassian.net/browse/FRW-1791
> FRW-1791 Integrated fixes for not fired kernel.terminate event in Glue.

- src/Pyz/Zed/Refund/RefundDependencyProvider.php
- Ticket: https://spryker.atlassian.net/browse/CC-29900
Core PRs:
- https://github.com/spryker/suite-nonsplit/pull/6908
- https://github.com/spryker/spryker/pull/9471
- https://github.com/spryker/spryker/pull/9892
> CC-29900 Fixed refund for marketplace integration.

- composer.json
- composer.lock
- config/Shared/config_default-docker.dev.php
- src/Pyz/Yves/EventDispatcher/EventDispatcherDependencyProvider.php
- src/Pyz/Yves/WebProfilerWidget/WebProfilerWidgetDependencyProvider.php
- src/Pyz/Zed/EventDispatcher/EventDispatcherDependencyProvider.php
- src/Pyz/Zed/WebProfiler/WebProfilerDependencyProvider.php
https://spryker.atlassian.net/browse/SDK-2600
> SDK-2600 Added profiler module.

- deploy.spryker-mpb2b.yml
- Ticket: https://spryker.atlassian.net/browse/CC-29911
> CC-29911 Adjusted deployment yaml file.

- composer.json
- composer.lock
- src/Pyz/Zed/CartCode/CartCodeDependencyProvider.php
- Ticket: https://spryker.atlassian.net/browse/CC-29851
> CC-21301: Fixed invalid checkout payment

- deploy.spryker-mpb2b.yml
- Ticket: https://spryker.atlassian.net/browse/CC-29960
> CC-29960: Added missing mail sender.

- composer.json
- composer.lock
- package-lock.json
- Ticket: https://spryker.atlassian.net/browse/CC-29918
> CC-29918 Fixed AddressForm's city field input type.

- composer.json
- composer.lock
- Ticket: https://spryker.atlassian.net/browse/CC-29931
> CC-29931 Fixed displaying grand total of merchant order after refund

- src/Pyz/Zed/AclMerchantPortal/AclMerchantPortalConfig.php
- Ticket: https://spryker.atlassian.net/browse/CC-17241
> CC-17241 Fixed creating merchant user while firstname and lastname already given.

- deploy.spryker-mpb2b.yml
- Ticket: https://spryker.atlassian.net/browse/CC-30090
> CC-30090 Adjust CORS configuration for demo shops GLUE APIs

- data/import/common/AT/payment_method_store.csv
- data/import/common/DE/payment_method_store.csv
- data/import/common/US/payment_method_store.csv
- data/import/common/common/payment_method.csv
- Ticket: https://spryker.atlassian.net/browse/CC-29892
- Core PR: None
> CC-29892: Adjust demo data to remove redundant payment method

- composer.lock
- src/Pyz/Client/ProductReview/ProductReviewDependencyProvider.php
- Ticket: https://spryker.atlassian.net/browse/CC-16486
> CC-16486 Fix the self-link for the product review resource.

- src/Pyz/Yves/CartPage/Theme/default/components/molecules/cart-sidebar-item/cart-sidebar-item.twig
- src/Pyz/Yves/CartPage/Theme/default/components/organisms/cart-sidebar/cart-sidebar.twig
- src/Pyz/Yves/CartPage/Theme/default/templates/page-layout-cart-preview/page-layout-cart-preview.twig
- src/Pyz/Yves/CartPage/Theme/default/templates/page-layout-cart/page-layout-cart.twig
- Ticket: https://spryker.atlassian.net/browse/CC-30037
> CC-30037: Fixed cart page product items sum display.

- src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/order-summary/order-summary.twig
- Ticket: https://spryker.atlassian.net/browse/CC-30665
> CC-30665 Fixed order item count on order detail page.

- composer.lock
- src/Pyz/Zed/Merchant/MerchantDependencyProvider.php
Ticket: https://spryker.atlassian.net/browse/CC-30403
Integration ticket: https://spryker.atlassian.net/browse/CC-30897
> CC- 30403: Added merchant expander bulk plugins execution.

- deploy.aop-b2b-testing.yml
- deploy.aop-demoshop-b2b.yml
- deploy.ci.acceptance.dynamic-store.yml
- deploy.ci.acceptance.mariadb.dynamic-store.yml
- deploy.ci.acceptance.mariadb.prefer-lowest.dynamic-store.yml
- deploy.ci.acceptance.mariadb.yml
- deploy.ci.acceptance.yml
- deploy.ci.api.dynamic-store.yml
- deploy.ci.api.mariadb.dynamic-store.yml
- deploy.ci.api.mariadb.yml
- deploy.ci.api.yml
- deploy.ci.functional.dynamic-store.yml
- deploy.ci.functional.mariadb.dynamic-store.yml
- deploy.ci.functional.mariadb.prefer-lowest.dynamic-store.yml
- deploy.ci.functional.mariadb.yml
- deploy.ci.functional.yml
- deploy.dev.dynamic-store.yml
- deploy.dev.yml
- deploy.dynamic-store.yml
- deploy.spryker-mpb2bs.yml
- deploy.yml
- Ticket: https://spryker.atlassian.net/browse/SC-15419
> SC-15419 Integrated the new version of Jenkins into the all public demoshops

- src/Pyz/Yves/ProductDetailPage/ProductDetailPageDependencyProvider.php
- src/Pyz/Yves/ProductDetailPage/Theme/default/views/pdp/pdp.twig
- Ticket: https://spryker.atlassian.net/browse/CC-31536
> CC-31536 Fixed PDP container key not found exception.

- .github/workflows/ci.yml
- Activate NPM checker for critical and high level vulnerabilities in CI
> Activate npm checker

- deploy.dev.yml
- tests/PyzTest/Yves/Application/Presentation/Controller/HomepageCest.php
- tests/PyzTest/Yves/Application/_support/ApplicationPresentationTester.php
- tests/PyzTest/Yves/Application/codeception.yml
- tests/PyzTest/Zed/AclEntity/codeception.yml
- tests/PyzTest/Zed/NavigationGui/Presentation/NavigationCRUDCest.php
- tests/PyzTest/Zed/NavigationGui/_support/NavigationGuiPresentationTester.php
- tests/PyzTest/Zed/Product/Business/ProductAbstractManagerTest.php
- tests/PyzTest/Zed/Product/Business/ProductConcreteManagerTest.php
- tests/PyzTest/Zed/ProductRelation/Presentation/ProductRelationCreateRelationCest.php
- tests/PyzTest/Zed/ProductRelation/_support/PageObject/ProductRelationCreatePage.php
- tests/PyzTest/Zed/ProductRelation/_support/ProductRelationPresentationTester.php
- Ticket: https://spryker.atlassian.net/browse/SUPESC-780
> SUPESC-780 Fixed failing automated tests on local environment. 

- .github/workflows/ci.yml
- Ticket: https://spryker.atlassian.net/browse/CC-31641
> CC-31641 Fixed hosts list and queue fot AT store.

- deploy.aop-b2b-testing.yml
- deploy.aop-demoshop-b2b.yml
- Ticket: https://spryker.atlassian.net/browse/APPS-10315
> [APPS-10315] Changed mb2 gateways with domains.

- composer.lock
- package-lock.json
- package.json
- Ticket: https://spryker.atlassian.net/browse/CC-31728
- Core PR: https://github.com/spryker/spryker/pull/10592
> CC-31728 Update npm dependencies

- composer.json
- composer.lock
- Ticket: https://spryker.atlassian.net/browse/CC-31792
- Core PR: https://github.com/spryker/spryker/pull/10599
> SUPESC-754 Fixed Shopping Lists unsharing.

- src/Pyz/Zed/ProductManagement/Presentation/_partials/product_volume_price_action_button.twig
- Ticket: https://spryker.atlassian.net/browse/CC-31801
> CC-31801 Fixed exception when setting merchant relation price.

- composer.json
- composer.lock
- src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/address-item-form-field-list/address-item-form-field-list.twig
- src/Pyz/Yves/CheckoutPage/Theme/default/views/address/address.twig
- Ticket: https://spryker.atlassian.net/browse/CC-31787
- Core PR: https://github.com/spryker/spryker-shop/pull/2421
> CC-31787 Fixed preselected address state for multiple addresses at checkout

- deploy.aop-b2b-testing.yml
- deploy.aop-demoshop-b2b.yml
- Ticket: https://spryker.atlassian.net/browse/APPS-10665
> [APPS-10665] Provided enpoints for TF related build.

- src/Pyz/Yves/ProductDetailPage/Theme/default/views/pdp/pdp.twig
- src/Pyz/Yves/ProductGroupWidget/Theme/default/components/molecules/color-selector/color-selector.twig
- Ticket: https://spryker.atlassian.net/browse/CC-31798
> CC-31798 Fix yves product color selectors

- src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/address-item-form-field-list/address-item-form-field-list.twig
- Ticket: https://spryker.atlassian.net/browse/CC-31782?focusedCommentId=435538
> CC-31782 Fixed address state for multiple addresses

- composer.json
- composer.lock
- Ticket: https://spryker.atlassian.net/browse/CC-29270
- Core PR: https://github.com/spryker/spryker/pull/10604
> CC-29270 Fixed merchant product offer storage memory leak.

- config/install/docker.ci.acceptance.robot.yml
- deploy.ci.acceptance.mariadb.robot.yml
- Ticket: https://spryker.atlassian.net/browse/CC-32135
> CC-32131 Fixed merchant portal and Product configurator build for CI acceptance configuration files.

- src/Pyz/Zed/Sales/SalesConfig.php
- Ticket: https://spryker.atlassian.net/browse/CC-31773
> CC-31773 Fixed issue with missing shipment price on Order Details page.

- deploy.aop-b2b-testing.yml
- deploy.aop-demoshop-b2b.yml
- Ticket: https://spryker.atlassian.net/browse/APPS-10665
> APPS-10665: Implemented endpoints for Terraform-related builds

- composer.lock
- src/Pyz/Yves/MerchantSalesReturnWidget/Theme/default/components/molecules/merchant-sales-return-create-form/merchant-sales-return-create-form.twig
- src/Pyz/Yves/MerchantSalesReturnWidget/Theme/default/components/molecules/separate-returns-by-merchant/separate-returns-by-merchant.ts
Ticket: https://spryker.atlassian.net/browse/CC-32187
> CC-21163 Fixed ability to create return for bundle products.

- src/Pyz/Yves/CompanyPage/Theme/default/components/molecules/business-unit-address-table/business-unit-address-table.twig
- src/Pyz/Yves/CompanyPage/Theme/default/components/molecules/permission-table/permission-table.twig
- src/Pyz/Yves/CompanyPage/Theme/default/components/molecules/role-table/role-table.twig
- src/Pyz/Yves/CompanyPage/Theme/default/components/molecules/user-table/user-table.twig
- src/Pyz/Yves/CompanyUserInvitationPage/Theme/default/components/molecules/invitation-table/invitation-table.twig
- src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/order-table/order-table.scss
- src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/order-table/order-table.twig
- src/Pyz/Yves/MultiCartPage/Theme/default/components/molecules/quote-table/index.ts
- src/Pyz/Yves/MultiCartPage/Theme/default/components/molecules/quote-table/quote-table.scss
- src/Pyz/Yves/MultiCartPage/Theme/default/components/molecules/quote-table/quote-table.twig
- src/Pyz/Yves/QuoteRequestAgentPage/Theme/default/components/molecules/quote-request-table/quote-request-table.twig
- src/Pyz/Yves/QuoteRequestAgentWidget/Theme/default/views/quote-request-agent-cancel-link/quote-request-agent-cancel-link.twig
- src/Pyz/Yves/QuoteRequestPage/Theme/default/components/molecules/quote-request-view-table/quote-request-view-table.twig
- src/Pyz/Yves/QuoteRequestWidget/Theme/default/views/quote-request-cancel-link/quote-request-cancel-link.twig
- src/Pyz/Yves/SalesReturnPage/Theme/default/templates/page-layout-sales-return/page-layout-sales-return.twig
- src/Pyz/Yves/SalesReturnPage/Theme/default/views/return-list/return-list.twig
- src/Pyz/Yves/SharedCartWidget/Theme/default/views/multi-cart-permission-actions/multi-cart-permission-actions.twig
- src/Pyz/Yves/ShopUi/Theme/default/components/atoms/table/table.scss
- src/Pyz/Yves/ShopUi/Theme/default/components/molecules/status/status.scss
- src/Pyz/Yves/ShopUi/Theme/default/components/molecules/table-action-link/table-action-link.scss
- src/Pyz/Yves/ShopUi/Theme/default/components/molecules/table-action-list/table-action-list.scss
- src/Pyz/Yves/ShopUi/Theme/default/components/molecules/table-action-list/table-action-list.twig
- src/Pyz/Yves/ShoppingListPage/Theme/default/components/molecules/shopping-list-overview-table/shopping-list-overview-table.twig
- src/Pyz/Yves/ShoppingListPage/Theme/default/views/shopping-list-dismiss-link/shopping-list-dismiss-link.twig
Ticket: https://spryker.atlassian.net/browse/CC-30070
> CC-30070 Fixed table actions alignment.

- src/Pyz/Yves/ShopUi/Theme/default/components/atoms/table/table.scss
- src/Pyz/Yves/ShopUi/Theme/default/components/molecules/table-action-list/table-action-list.scss
Ticket: https://spryker.atlassian.net/browse/CC-30070
> CC-30070 Fixed table indents.

- composer.lock
- data/import/common/common/glossary.csv
- Ticket: https://spryker.atlassian.net/browse/FRW-6331
> FRW-6331 Data Exchange API Complex Endpoints for GET request.

- composer.lock
- src/Pyz/Yves/CustomerPage/CustomerPageDependencyProvider.php
- src/Pyz/Yves/Security/SecurityDependencyProvider.php
- src/Pyz/Yves/ShopApplication/ShopApplicationDependencyProvider.php
- src/Pyz/Yves/Validator/ValidatorDependencyProvider.php
- src/Pyz/Zed/Application/ApplicationDependencyProvider.php
- src/Pyz/Zed/MerchantPortalApplication/MerchantPortalApplicationDependencyProvider.php
- src/Pyz/Zed/Security/SecurityDependencyProvider.php
- src/Pyz/Zed/Validator/ValidatorDependencyProvider.php
- Ticket: https://spryker.atlassian.net/browse/FRW-5940
> FRW-5940 Updated spryker to support symfony security modules v6

- composer.json
- composer.lock
- Ticket: https://spryker.atlassian.net/browse/SDK-5711
> SDK-5711 Update `evaluator` dependency.

- deploy.aop-b2b-testing.yml
- deploy.aop-demoshop-b2b.yml
- Ticket: https://spryker.atlassian.net/browse/ACP-2217
> ACP-2217: Stripe missing domains

- composer.lock
- Ticket: https://spryker.atlassian.net/browse/FRW-7414
> FRW-7414 Updated composer.lock

- config/install/docker.ci.acceptance.dynamic-store.robot.yml
- deploy.ci.acceptance.mariadb.dynamic-store.robot.yml
FRW-7454 added new config files for UI CI Dynamic Multistore
- Ticket: [FRW-7454 added new config files for UI CI Dynamic Multistore](https://spryker.atlassian.net/browse/FRW-7454]
> FRW-7454 added new config files for UI CI Dynamic Multistore

- .github/workflows/ci.yml
- composer.lock
- deploy.ci.api.mariadb.dynamic-store.robot.yml
- Ticket: https://spryker.atlassian.net/browse/FRW-7451
> FRW - 7451 new job for robot api tests dynamic multistore

- composer.lock
СС-33122 Updated composer.loc file for robot container
- Ticket: [https://spryker.atlassian.net/browse/CC-33122]
> СС-33122 Updated composer.loc file for robot container

- composer.lock
- Ticket: https://spryker.atlassian.net/browse/ACP-2269
- Updated `spryker/sales`.
- Updated `spryker/sales-payment`.
> ACP-2269 integration

- deploy.ci.acceptance.mariadb.dynamic-store.yml
СС-33164 added configurator settings into yml file
Overview
- Ticket: [https://spryker.atlassian.net/browse/CC-33164]
> СС-33164 added configurator settings into yml file

- composer.json
- composer.lock
- data/import/common/common/glossary.csv
- src/Pyz/Zed/Console/ConsoleDependencyProvider.php
- src/Pyz/Zed/Oms/OmsDependencyProvider.php
- src/Pyz/Zed/Synchronization/SynchronizationDependencyProvider.php
Tickets: 
- https://spryker.atlassian.net/browse/FRW-7452
- https://spryker.atlassian.net/browse/FRW-7291
- https://spryker.atlassian.net/browse/FRW-7432
- https://spryker.atlassian.net/browse/SUPESC-813
- https://spryker.atlassian.net/browse/SUPESC-808
- https://spryker.atlassian.net/browse/FRW-7463
- https://spryker.atlassian.net/browse/FRW-7477
- https://spryker.atlassian.net/browse/FRW-7329
- https://spryker.atlassian.net/browse/FRW-6955
> FRW-6879 Integrations

- deploy.ci.acceptance.mariadb.dynamic-store.robot.yml
- Ticket: [https://spryker.atlassian.net/browse/CC-33164]
> CC-33164  updated configuration for configurable product

- config/install/docker.ci.acceptance.dynamic-store.robot.yml
- deploy.ci.acceptance.mariadb.dynamic-store.robot.yml
- deploy.dev.dynamic-store.yml
- deploy.dynamic-store.yml
- Ticket: https://spryker.atlassian.net/browse/FRW-6380
> FRW-6380 Adjusted deploy config.

- composer.lock
- data/import/common/common/glossary.csv
- Ticket: https://spryker.atlassian.net/browse/FRW-7821
> FRW-7296 Integration

- data/import/common/common/product_review.csv
Ticket: https://spryker.atlassian.net/browse/CC-33419
> CC-33419 Adjusted product rating.

- .github/workflows/ci.yml
- Adjusted GA configuration to enable retry for flaky tests
> Adjusted GA configuration.

- composer.json
- composer.lock
- Ticket: https://spryker.atlassian.net/browse/CC-33530
> CC-33530: Adjusted list of possible price dimensions.

- src/Pyz/Zed/CommentSalesConnector/Presentation/Sales/list.twig
closes [CC-33529](https://spryker.atlassian.net/browse/CC-33529)
> CC-33529: Fixed bo scroll to comment section

- .github/workflows/ci.yml
- .github/workflows/robot-ui-e2e-tests.yml
- composer.lock
- deploy.ci.acceptance.mariadb.cypress.yml
- deploy.ci.acceptance.mariadb.dynamic-store.cypress.yml
Added new UI ci yml with jobs
- Ticket: https://spryker.atlassian.net/browse/CC-33309
> Added new UI ci yml with jobs

- .github/workflows/robot-ui-e2e-tests.yml
- Ticket: https://spryker.atlassian.net/browse/CC-33768
> CC-33768: Added fixes for the "Robot Regression UI E2E"

- data/import/production/full_US.yml
- Ticket: https://spryker.atlassian.net/browse/CC-33735
> CC-33735 Fixed production import manifest file

- .github/workflows/up-merge-latest-release-to-master-deploy.yml
- Ticket: https://spryker.atlassian.net/browse/CC-33310
- Introduced the workflow to auto-merge the latest release to the "master-deploy" branch.
> CC-33310: Introduced the workflow to auto-merge the latest release to the "master-deploy" branch.

- composer.json
- composer.lock
- package-lock.json
- tests/PyzTest/Zed/TestifyBackendApi/codeception.dynamic.fixtures.yml
- Ticket: https://spryker.atlassian.net/browse/CC-34000
> Fixed issues with Commission integration.

- composer.lock
- Ticket: https://spryker.atlassian.net/browse/CC-34112
> CC-34112: Shared cart fatal error integration

- config/Shared/config_default.php
- Ticket: https://spryker.atlassian.net/browse/ACP-3655
- RG : https://release.spryker.com/release-groups/view/5450
> ACP-2626: Stripe marketplace payment flow -fix

- public/MerchantPortal/redirect.php
> ACP-3675: Update redirect.php

- src/Pyz/Zed/Transfer/TransferConfig.php
> Added Transfer configuration.

- composer.lock
Tickets:
- CC-34071
- ACP-3677
> MP payment transfers with commission fixes for OMS (patches)

- composer.lock
- src/Pyz/Zed/MerchantPortalApplication/Communication/MerchantPortalApplicationCommunicationFactory.php
- src/Pyz/Zed/MerchantPortalApplication/MerchantPortalApplicationConfig.php
- Ticket:  https://spryker.atlassian.net/browse/FRW-8932
> FRW-8932 Marketplace homepage fix integration.

- composer.lock
- src/Pyz/Yves/CatalogPage/CatalogPageConfig.php
- Ticket: https://spryker.atlassian.net/browse/CC-13685
> CC-13685: Updated product quantity and total in Mini Cart Widget from catalog AJAX add-to-cart action.

- composer.lock
- config/Zed/cronjobs/jenkins.php
- config/Zed/navigation.xml
- src/Pyz/Zed/Console/ConsoleDependencyProvider.php
- Ticket: https://spryker.atlassian.net/browse/FRW-8766
> FRW-8766 Order matrix performance improvement integration.

- composer.lock
- config/Shared/config_default-docker.dev.php
- src/Pyz/Zed/SalesPaymentMerchant/SalesPaymentMerchantConfig.php
- Ticket: https://spryker.atlassian.net/browse/ACP-3813
- Core PR: https://github.com/spryker/suite-nonsplit/pull/8983
- Enabled the expense support for the marketplace payments.
> ACP-3558 Merchant payment expense support.

- composer.lock
- src/Pyz/Zed/AclMerchantPortal/AclMerchantPortalDependencyProvider.php
- Ticket: https://spryker.atlassian.net/browse/ACP-3824
> ACP-3824: updated composer, Added acl plugin

- composer.lock
- src/Pyz/Zed/Console/ConsoleDependencyProvider.php
- src/Pyz/Zed/CustomerAccessStorage/Persistence/Propel/Schema/spy_unauthenticated_customer_access_storage.schema.xml
- src/Pyz/Zed/Event/EventConfig.php
- src/Pyz/Zed/SynchronizationBehavior/SynchronizationBehaviorConfig.php
- src/Pyz/Zed/TaxProductStorage/Persistence/Propel/Schema/spy_tax_product_storage.schema.xml
- Ticket: https://spryker.atlassian.net/browse/CC-33982
- IG ticket: https://spryker.atlassian.net/browse/CC-34373
> CC-33982: P&S optimisation.

- composer.lock
- package-lock.json
- Ticket: https://spryker.atlassian.net/browse/CC-34484
> CC-34484: Session locking issue after recent integration on B2C and B2C Marketplace demo shops.

- composer.json
- composer.lock
- src/Pyz/Zed/DynamicEntity/DynamicEntityDependencyProvider.php
- Ticket:  https://spryker.atlassian.net/browse/FRW-9121
> FWR-9121 Fixed broken robot test

- composer.lock
- src/Pyz/Zed/MerchantCommission/MerchantCommissionConfig.php
- Ticket: https://spryker.atlassian.net/browse/CC-34500
> CC-34500 Adjusted merchant commission calculation to not rely on price mode per store configuration.

- src/Pyz/Zed/DynamicEntity/data/installer/configuration.json
- Ticket: https://spryker.atlassian.net/browse/FRW-8761
> FRW-8761 Adjusted configuration

- composer.lock
- src/Pyz/Zed/MerchantGui/MerchantGuiDependencyProvider.php
- Ticket: https://spryker.atlassian.net/browse/FRW-9176
> FRW-9176 Integration.

- composer.lock
- src/Pyz/Yves/CheckoutPage/CheckoutPageConfig.php
Tickets:
- https://spryker.atlassian.net/browse/FRW-1877
- https://spryker.atlassian.net/browse/SUPESC-866
- https://spryker.atlassian.net/browse/FRW-9132
- https://spryker.atlassian.net/browse/FRW-8906
> FRW-9030 Integrations part 5

- composer.json
- composer.lock
- package-lock.json
- src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.scss
- src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.twig
- src/Pyz/Yves/CatalogPage/Theme/default/templates/page-layout-catalog/page-layout-catalog.twig
- tsconfig.mp.json
- Ticket: https://spryker.atlassian.net/browse/CC-34672
> CC-34672 Collapsible category tree integraton

- composer.json
- composer.lock
- config/Zed/navigation.xml
> Anallytics integration

- config/install/ci.yml
- config/install/development.yml
- config/install/docker.ci.acceptance.cypress.yml
- config/install/docker.ci.acceptance.dynamic-store-off.robot.yml
- config/install/docker.ci.acceptance.dynamic-store-off.yml
- config/install/docker.ci.acceptance.robot.yml
- config/install/docker.ci.acceptance.yml
- config/install/docker.ci.api.dynamic-store-off.yml
- config/install/docker.ci.api.yml
- config/install/docker.yml
- config/install/testing.yml
- Ticket: https://spryker.atlassian.net/browse/FRW-9241
> FRW-9241 Adjusted installation configs

- composer.lock
- package-lock.json
- Ticket:https://spryker.atlassian.net/browse/CC-34732
> CC-34732 Update Summernote dependency

- .robot/Dockerfile
- composer.lock
- package-lock.json
- Ticket: https://spryker.atlassian.net/browse/FRW-9423
- Core PR: https://github.com/spryker/spryker/pull/11212
> FRW-9423 Fixed twig error for product view in Merchant Portal.

- deploy.aop-demoshop-b2b.yml
- Ticket: https://spryker.atlassian.net/browse/ACP-4427
> ACP-4427: Enabled DMS for ACP

- src/Pyz/Service/DataExport/DataExportDependencyProvider.php
- Ticket: https://spryker.atlassian.net/browse/CC-34874
> CC-34874 Fixed Merchant Commission export

- deploy.aop-demoshop-b2b.yml
- Ticket: https://spryker.atlassian.net/browse/ACP-4618
> ACP-4618: Fixed aop deploy

- deploy.aop-b2b-testing.yml
- deploy.aop-demoshop-b2b.yml
- Ticket: https://spryker.atlassian.net/browse/ACP-4378
> ACP-4378: Fixed url for acp testing build

- .github/workflows/ci.yml
- Ticket: https://spryker.atlassian.net/browse/FRW-9599
> FRW-9599 Fixed hackaton robot tests.

- composer.lock
- config/Shared/config_default-docker.dev.php
- config/Shared/config_default.php
- src/Pyz/Zed/MerchantPortalApplication/MerchantPortalApplicationDependencyProvider.php
- src/Pyz/Zed/SecurityMerchantPortalGui/SecurityMerchantPortalGuiConfig.php
- Ticket: https://spryker.atlassian.net/browse/FRW-9299
> FRW-9299 Integrated Profiler enabling. 

- composer.lock
- Ticket: https://spryker.atlassian.net/browse/SUPESC-897
- https://release.spryker.com/release/pull-request/11247
> SUPESC-897 Improved performance of BundledProductTable. 

- composer.lock
- Ticket: https://spryker.atlassian.net/browse/CC-35021
> CC-35021: Updated cypress hash.

- .github/workflows/ci.yml
- .github/workflows/robot-ui-e2e-tests.yml
- Ticket: https://spryker.atlassian.net/browse/FRW-9711
> FRW-9444 Trigger jobs PR on unlabeled.

- composer.lock
- package-lock.json
- Ticket: https://spryker.atlassian.net/browse/CC-34804
> CC-34804: Exception on Manage Company Roles tests

- composer.lock
- package-lock.json
- package.json
- src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/shipment-sidebar/shipment-sidebar.twig
- src/Pyz/Yves/ShopUi/Theme/default/components/molecules/date-time-picker/date-time-picker.scss
- src/Pyz/Yves/ShopUi/Theme/default/components/molecules/date-time-picker/date-time-picker.ts
- src/Pyz/Yves/ShopUi/Theme/default/components/molecules/date-time-picker/date-time-picker.twig
Ticket: https://spryker.atlassian.net/browse/CC-35203
> CC-35203 Fixes tests and adds datepicker plugin

- composer.lock
- src/Pyz/Zed/ZedNavigation/ZedNavigationConfig.php
- Tickets: 
- https://spryker.atlassian.net/browse/SUPESC-942
- https://spryker.atlassian.net/browse/SUPESC-941
> SUPESC-941 + SUPESC-942 Merchant Portal performance improvements.

- composer.lock
- Ticket: https://spryker.atlassian.net/browse/FRW-9988
> FRW-9988: Integration

- deploy.ssp-ssp-b2bmp.yml
- src/Pyz/Yves/SspInquiryManagement/Theme/default/views/detail/detail.twig
> FRW-731: display asset details at inquiry details

- src/Pyz/Yves/ShopUi/Theme/default/components/molecules/user-navigation/user-navigation.twig
> Ssp master dashboard bugfixes

- composer.lock
- data/import/common/common/glossary.csv
- src/Pyz/Yves/MultiCartWidget/Theme/default/components/molecules/mini-cart-detail/mini-cart-detail.twig
- src/Pyz/Zed/Sales/SalesConfig.php
- Ticket:https://spryker.atlassian.net/browse/CC-22722
> CC-22722: Order Sequence Generation integration

- composer.lock
- Ticket: https://spryker.atlassian.net/browse/FRW-9661
> Integration: FRW-9661, FRW-9444, FRW-9438

- config/Shared/config_default.php
- Ticket: https://spryker.atlassian.net/browse/SUPESC-887
> SUPESC-887: Integration

- src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/shipment-sidebar/shipment-sidebar.twig
- src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/order-filters/order-filters.twig
- src/Pyz/Yves/QuoteRequestAgentPage/Theme/default/views/quote-request-edit/quote-request-edit.twig
- src/Pyz/Yves/ShopUi/Theme/default/components/molecules/date-time-picker/date-time-picker.scss
- src/Pyz/Yves/ShopUi/Theme/default/components/molecules/date-time-picker/date-time-picker.ts
- src/Pyz/Yves/ShopUi/Theme/default/components/molecules/date-time-picker/date-time-picker.twig
Ticket: https://spryker.atlassian.net/browse/CC-35415
> CC-35415: B2B yves range date picker has poor accessibility

- tests/PyzTest/Zed/CmsGui/Presentation/CmsGuiCreatePageCest.php
- tests/PyzTest/Zed/CmsGui/_support/CmsGuiPresentationTester.php
- Ticket: https://spryker.atlassian.net/browse/CC-35490
Improvements
- Fixed CmsGuiCreatePageCest
> CC-35490 Fixed flaky CMS page test.

- config/install/destructive.yml
- Ticket: https://spryker.atlassian.net/browse/CC-35103
IMPORTANT: These changes should never be merged into master, only into the master-deploy branch.
- Added publish and sync into the destructive deployment to avoid flaky tests.
> CC-35103 Add P&S into destructive deployment.

- data/import/common/common/glossary.csv
- src/Pyz/Yves/CartPage/Theme/default/components/molecules/cart-sidebar-item/cart-sidebar-item.scss
- src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.scss
- src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.twig
- src/Pyz/Yves/MerchantOpeningHoursWidget/Theme/default/components/molecules/date-information-item/date-information-item.scss
- src/Pyz/Yves/MerchantPage/Theme/default/components/molecules/information-item/information-item.scss
- src/Pyz/Yves/ProductDetailPage/Theme/default/components/molecules/product-configurator/product-configurator.scss
- src/Pyz/Yves/ShopUi/Theme/default/components/atoms/select/select.scss
- src/Pyz/Yves/ShopUi/Theme/default/components/molecules/custom-select/custom-select.ts
- src/Pyz/Yves/ShopUi/Theme/default/components/molecules/date-time-picker/date-time-picker.twig
- src/Pyz/Yves/ShopUi/Theme/default/components/molecules/form/form.scss
- src/Pyz/Yves/ShopUi/Theme/default/components/molecules/privacy-navigation/privacy-navigation.scss
- src/Pyz/Yves/ShopUi/Theme/default/components/molecules/product-item-list/product-item-list.scss
- src/Pyz/Yves/ShopUi/Theme/default/components/molecules/table-action-list/table-action-list.scss
- src/Pyz/Yves/ShopUi/Theme/default/styles/settings/_color.scss
- src/Pyz/Yves/ShoppingListPage/Theme/default/views/shopping-list/shopping-list.twig
- src/Pyz/Yves/ShoppingListWidget/Theme/default/views/shopping-list-add-items/shopping-list-add-items.twig
- Ticket: https://spryker.atlassian.net/browse/CC-35691
> CC-35691: fixes accessibility

- composer.lock
- public/MerchantPortal/redirect.php
- tests/PyzTest/Yves/Checkout/Process/Steps/ShipmentStepTest.php
- Ticket: https://spryker.atlassian.net/browse/CC-35650
> CC-35650 April 2025 integrations.

- composer.lock
- package-lock.json
- src/Orm/Zed/SspAssetManagement/Persistence/SpySalesOrderItemSspAsset.php
- src/Orm/Zed/SspAssetManagement/Persistence/SpySalesOrderItemSspAssetQuery.php
- src/Pyz/Yves/CartPage/CartPageDependencyProvider.php
- src/Pyz/Yves/ClickAndCollectPageExample/ClickAndCollectPageExampleConfig.php
- src/Pyz/Yves/Router/RouterDependencyProvider.php
- src/Pyz/Yves/ShopApplication/ShopApplicationDependencyProvider.php
- src/Pyz/Yves/Twig/TwigDependencyProvider.php
- src/Pyz/Zed/Cart/CartDependencyProvider.php
- src/Pyz/Zed/Sales/SalesDependencyProvider.php
https://spryker.atlassian.net/browse/SSP-1015
> SSP-1015 Fixed service reschedule.

- .github/actions/job-slack-notifications/action.yml
- Ticket: https://spryker.atlassian.net/browse/CC-35773
> CC-35773 Improved failed Github action jobs notifications.

- src/Pyz/Yves/AgentPage/AgentPageConfig.php
> CC-35509: trigger ci

- .github/actions/job-slack-notifications/action.yml
- .github/workflows/ci.yml
- .github/workflows/robot-ui-e2e-tests.yml
- Ticket: https://spryker.atlassian.net/browse/CC-35771
> CC-35509: remove weekly ci

- tests/PyzTest/Glue/Checkout/RestApi/CompanyBusinessUnitAddressCheckoutDataRestApiCest.php
- Ticket: https://spryker.atlassian.net/browse/CC-35515
> CC-35515 Fixed CompanyBusinessUnitAddressCheckoutDataRestApiCest.

- src/Pyz/Yves/CartPage/Theme/default/components/molecules/product-cart-item/product-cart-item.twig
- src/Pyz/Yves/ShopUi/Theme/default/components/molecules/product-card-item/product-card-item.twig
- Ticket: https://spryker.atlassian.net/browse/SSP-1020
> SSP-1020 Fixed issue with missing assets & scheduled date data in product info.

- composer.json
- composer.lock
- src/Pyz/Zed/Event/EventDependencyProvider.php
- src/Pyz/Zed/Stock/StockConfig.php
- Ticket: https://spryker.atlassian.net/browse/CC-35836
- Ticket: https://spryker.atlassian.net/browse/SUPESC-854
> CC-35836: Added queue-based warehouse update functionality.

- deploy.scos2-b2bmpperf.yml
> deploy.scos2-b2bmpperf.yml

- src/Pyz/Zed/Twig/TwigDependencyProvider.php
> Itegration

- deploy.spryker-b2bmp-staging.yml
- Ticket: https://spryker.atlassian.net/browse/SC-22955
> SC-22955: Added deploy file for staging env with DMS on

- composer.lock
- src/Pyz/Zed/Store/StoreDependencyProvider.php
- Ticket: https://spryker.atlassian.net/browse/CC-35846
> CC-35846: Added timezone to Order Table filters.

- composer.json
- composer.lock
- config/Zed/navigation.xml
- tests/PyzTest/Zed/TestifyBackendApi/codeception.dynamic.fixtures.yml
- Ticket: https://spryker.atlassian.net/browse/AE-212
- Core PR: https://github.com/spryker/spryker/pull/11621
- B2B: https://github.com/spryker-shop/b2b-demo-shop/pull/713
- Introduced Measurement Unit menu item in the back office Administration menu.
> AE-212 Integration Measurement Unit Gui

- composer.json
- composer.lock
- src/Pyz/Yves/CheckoutPage/Theme/default/templates/page-layout-order-submitted/page-layout-order-submitted.twig
- Ticket: https://spryker.atlassian.net/browse/CC-36088
> СС-36088: Fixed shipment expense calculation in case of a multi-shipment.

- src/Pyz/Yves/AgentWidget/Theme/default/components/molecules/agent-control-item/agent-control-item.twig
- src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/category-card/category-card.twig
- src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/category-list-item/category-list-item.twig
- src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.twig
- src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/suggestion-links-list/suggestion-links-list.twig
- src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/suggestion-product/suggestion-product.twig
- src/Pyz/Yves/CmsSearchPage/Theme/default/components/molecules/search-cms-results/search-cms-results.twig
- src/Pyz/Yves/MerchantProductOfferWidget/Theme/default/components/molecules/merchant-product-offer-item/merchant-product-offer-item.twig
- src/Pyz/Yves/MerchantProductWidget/Theme/default/components/molecules/merchant-product-item/merchant-product-item.twig
- src/Pyz/Yves/MerchantRelationRequestPage/Theme/default/views/merchant-relation-request-details/merchant-relation-request-details.twig
- src/Pyz/Yves/MerchantRelationshipPage/Theme/default/views/detail/detail.twig
- src/Pyz/Yves/MerchantWidget/Theme/default/components/molecules/sold-by-merchant/sold-by-merchant.twig
- src/Pyz/Yves/ProductDetailPage/Theme/default/views/pdp/pdp.twig
- src/Pyz/Yves/ProductSetListPage/Theme/default/components/molecules/product-set-card/product-set-card.twig
- src/Pyz/Yves/QuoteRequestAgentWidget/Theme/default/components/atoms/request-button/request-button.twig
- src/Pyz/Yves/SalesReturnPage/Theme/default/components/molecules/return-overview/return-overview.twig
- src/Pyz/Yves/SharedCartPage/Theme/default/views/cart-share/cart-share.twig
- src/Pyz/Yves/SharedCartPage/Theme/default/views/dismiss-confirm/dismiss-confirm.twig
- src/Pyz/Yves/ShopUi/Theme/default/components/molecules/action-card/action-card.twig
- src/Pyz/Yves/ShopUi/Theme/default/components/molecules/banner/banner.twig
- src/Pyz/Yves/ShopUi/Theme/default/components/molecules/navigation-icon-list/navigation-icon-list.twig
- src/Pyz/Yves/ShopUi/Theme/default/components/molecules/navigation-list/navigation-list.twig
- src/Pyz/Yves/ShopUi/Theme/default/components/molecules/navigation-multilevel-node/navigation-multilevel-node.twig
- src/Pyz/Yves/ShopUi/Theme/default/components/molecules/product-card-item/product-card-item.twig
- src/Pyz/Yves/ShopUi/Theme/default/components/molecules/product-item-list/product-item-list.twig
- src/Pyz/Yves/ShopUi/Theme/default/components/molecules/product-item/product-item.twig
- src/Pyz/Yves/ShoppingListPage/Theme/default/views/shopping-list-dismiss-confirm/shopping-list-dismiss-confirm.twig
- Ticket: https://spryker.atlassian.net/browse/FRW-10736
> FRW-10736 Integration.

- package-lock.json
- Ticket: https://spryker.atlassian.net/browse/CC-36096
> CC-36099: fixes security issue with node modules

- deploy.aop-b2b-testing.yml
- deploy.aop-consultant-b2c.yml
- deploy.aop-demoshop-b2b.yml
- deploy.scos2-b2bmp.yml
- deploy.scos2-b2bmpperf.yml
- deploy.spryker-b2bmp.yml
- deploy.spryker-mp-b2b.yml
- deploy.spryker-mpb2bs.yml
- deploy.spryker-scosb2bmp.yml
> Reverted deploy files [skip ci]

- data/import/common/common/glossary.csv
- src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/order-detail/order-detail.twig
- src/Pyz/Yves/SalesOrderAmendmentWidget/Theme/default/components/molecules/order-amendment/order-amendment.twig
- src/Pyz/Yves/ShopUi/Theme/default/components/molecules/action-bar/action-bar.scss
- src/Pyz/Yves/ShopUi/Theme/default/components/molecules/navigation-sidebar-item/navigation-sidebar-item.scss
- Ticket: https://spryker.atlassian.net/browse/CC-36109
> CC-36109: button layout on order details page

- composer.lock
- src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
Ticket: https://spryker.atlassian.net/browse/SUPESC-789
> SUPESC-789 Super attributes don't show values maintained in Backoffice.

- composer.json
- composer.lock
Ticket: https://spryker.atlassian.net/browse/CC-36115
> CC-36115 Integrated bugfixes.

- tests/PyzTest/Yves/Customer/Presentation/CustomerAddressCest.php
- Ticket: https://spryker.atlassian.net/browse/CC-35660
- Core PR: no core PR
> CC-35660: Skip CustomerAddressCest

- src/Pyz/Zed/DataImport/Business/Model/DiscountVoucher/DiscountVoucherWriterStep.php
- Ticket: https://spryker.atlassian.net/browse/CC-35970
- Core PR: No core PR
The purpose of this PR is to add additional logs if CI failed during the build on the data import step.
> CC-35970: Flaky CI. Data Import discount voucher failed

- composer.lock
- Ticket: https://spryker.atlassian.net/browse/CC-36208
> Weekly integrations.

- deploy.aop-b2b-testing.yml
- deploy.aop-consultant-b2c.yml
- deploy.aop-demoshop-b2b.yml
- deploy.spryker-b2bmp.yml
- Ticket: https://spryker.atlassian.net/browse/SC-23578
> SC-23578: Added Otel extension into ACP deploy files

- composer.lock
- Ticket: https://spryker.atlassian.net/browse/CC-35974
> CC-35974: Added/adjusted helpers to cover missing SAPI tests.

- composer.lock
> CC-36111: Updated cypress tests.

- config/Shared/config_default.php
> Fixing open ai api key loading in config

- .robot/Dockerfile
- Ticket: https://spryker.atlassian.net/browse/CC-36431
- Locked browser library version
> CC-36431 Hotfix Robot UI tests execution

- config/install/destructive.yml
- Ticket: https://spryker.atlassian.net/browse/FRW-11070
> Adjusted distructive

- composer.lock
> CC-36466 Bugfixes integration.
